### ISSUE TITLE
[Proxy] Assign categories to livechat conversations on close #11445

### ISSUE THREAD

**Issue by mrsimpson** [assistify/Rocket.Chat#15]
_From @andytipp on August 14, 2017 8:25_

**Current state**
When closing a conversation, it currently shows an empty text field. 

**Preferred state**
To help categorization of closed conversations, there should be a list of categories when closing a conversation. The user can then assign categories to the closed conversation. There needs to be a way to configure the list of categories (add, edit, remove) 

_Copied from original issue: mrsimpson/Rocket.Chat#71_

**Comment by mrsimpson** [comment]
the closing of conversations is currently our own UI. This should - however - be included in the rocket.chat core as well

**Comment by ruKurz** [comment]
This close dialog is purposed for reporting. Since the requirements can be very individual here, the dialog should perform a configurable form, that allows to categorize, add some meta data and offer some predefined selections.

This dialog should be optional, and therefor an activation / deactivation is required:
assistify#24

**Comment by janrudolph** [comment]
Moved to Rocket.Chat https://github.com/RocketChat/feature-requests/issues/672
