### ISSUE TITLE
Threads - Welcome message

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#452]
An user who creates a new thread does not get any hint which users were invited. The user might think that the user has opened a new, blank channel. 

**To-Do:** 
Let Rocket.Cat post a message, that others joined the thread automatically, for instance: 

> "Thanks for creating a thread! In order to help you, I invited Peter, Thomas, Julie and five more people. Happy chatting!"

**Comment by mrsimpson** [comment]
![image](https://user-images.githubusercontent.com/17176678/45081716-1970c900-b0f8-11e8-8870-8e9bc88e7e07.png)

@janrudolph As you said the most important part is that the user has the feeling that something's happening. Due to the redundancy of the members list and the additional complexity, I left out the member names and went for a static message.

Fixed with 845740c7cb8ffa26ce616ab57135eb5b305b657e
