### ISSUE TITLE
Solve performance issues by reducing the conversation analysis triggers

### ISSUE THREAD

**Issue by ruKurz** [assistify/Rocket.Chat#551]
# Actual behavior
Currently `onMessageSent`, `onMessageEdited` and `onMessageDeleted` a smarti analysis is triggered. Since we enabled Smarti in all `channels` and `groups` this leads to a high CPU usage (Smarti).

# Expected behavior
Only if a user has opened the knowledge base Smarti analysis should be triggered when sending, editing oder deleting a message

# Solution
1. Check if the Knowledge Base is opened
2. If the Knowledge Base is opened, append the callback-URL
3. If the Knowledge Base is closed, do not append the callback-URL

**Comment by mrsimpson** [comment]
It's not as easy as it looks like:

- Requests to Smarti are sent from the server, actually independent of a consumer listening at all
- The widget being opened is a client interaction which can happen multiple times at once

=>

- Server-side, on the given events, a `POST` to Smarti should never be triggered
- Client-side, an additional event requesting the analysis should be issued
  - once the widget is being opened (we may not need this, I believe the widget already does this)
  - once the widget is visible, a message is sent, edited, deleted, should trigger an analysis request to Smarti *via the server*.  An additional Method in the widget backend is necessary in order to achieve this.

To be validated:
With multiple clients attached, an analysis for the same conversation might be triggered multiple times.
- Can Smarti recognize this already and just return the cached result?
- Should the actual http-request to Smarti be prevented by storing the last analysis timestamp?
